# Generated by Django 4.2.6 on 2023-10-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50)),
                ('cDesc', models.TextField(help_text='Course Description.')),
                ('cNum', models.IntegerField(help_text='Course Number.')),
                ('cHours', models.IntegerField(help_text='Course Credit Hours.')),
                ('cSubject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=50)),
                ('dType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.core')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.core')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.program')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curName', models.CharField(max_length=50)),
                ('curHours', models.IntegerField(help_text='Curriculum total hours.')),
                ('degreeRequirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degreerequirements')),
                ('degreeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degreetype')),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='degreeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degreetype'),
        ),
    ]
